### ISSUE TITLE
Panic in check_stop_streaming

### ISSUE THREAD

**Issue by petuhovskiy** [zenithdb/zenith#1103]
I was looking at [failed CI job](https://app.circleci.com/pipelines/github/zenithdb/zenith/3975/workflows/18cccb7e-c017-4f2e-89f2-481e8bb6d609/jobs/35492/steps), where `test_remote_storage_backup_and_restore` timed out and tried to reproduce it locally. When I ran the test locally, it hanged on `--sync-safekeepers` inside `zenith pg start`. The reason seems to be panic in safekeeper.log

<details>
<summary>Full safekeeper.log</summary>

```
2022-01-12T13:51:40.976155Z  INFO version: git:f936735966cd725ac95a6110d0c741b4d95492f6
2022-01-12T13:51:40.976766Z  INFO Starting safekeeper on localhost:15002
2022-01-12T13:51:40.976851Z  INFO daemonizing...
2022-01-12T13:51:40.979678Z  INFO Success, daemonized
2022-01-12T13:51:40.992412Z  INFO Starting a http endpoint at 127.0.0.1:15003
2022-01-12T13:51:40.995540Z DEBUG parsed 2 headers
2022-01-12T13:51:40.995585Z DEBUG incoming body is empty
2022-01-12T13:51:40.996555Z  INFO GET /v1/status 200 OK
2022-01-12T13:51:40.997304Z DEBUG flushed 109 bytes
2022-01-12T13:51:40.997866Z DEBUG read eof
2022-01-12T13:51:41.004447Z DEBUG parsed 5 headers
2022-01-12T13:51:41.004498Z DEBUG incoming body is empty
2022-01-12T13:51:41.004807Z  INFO GET /v1/status 200 OK
2022-01-12T13:51:41.004931Z DEBUG flushed 109 bytes
2022-01-12T13:51:41.006419Z DEBUG read eof
2022-01-12T13:51:41.047486Z DEBUG accepted connection from 127.0.0.1:41514
2022-01-12T13:51:41.055485Z  INFO {tid=5}: creating timeline dir 5bfbbde44c951f0ff7dc973c7412060a, create is True
2022-01-12T13:51:41.056647Z  INFO {tid=5}: loading control file ./5bfbbde44c951f0ff7dc973c7412060a/safekeeper.control, create=True
2022-01-12T13:51:41.059019Z  INFO {tid=5}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: start handshake with wal proposer 127.0.0.1:41514 sysid 0 timeline 0
2022-01-12T13:51:41.059240Z  INFO callmemaybe. thread_main. subscribe callback request for timelineid=5bfbbde44c951f0ff7dc973c7412060a tenantid=46e12f8e417c4bd0a2717cc59e10bcc1
2022-01-12T13:51:41.069731Z  INFO {tid=5}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed greeting from proposer [27, 244, 95, 240, 50, 84, 185, 104, 219, 21, 42, 30, 156, 187, 245, 48], sending term 0
2022-01-12T13:51:41.073375Z  INFO {tid=5}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed VoteRequest for term 1: VoteResponse { term: 1, vote_given: 1, flush_lsn: 0/0, truncate_lsn: 0/0, term_history: [] }
2022-01-12T13:51:41.074598Z  WARN {tid=5}: query handler for START_WAL_PUSH postgresql://no_user:@localhost:15000 failed: failed to run ReceiveWalConn: connection closed unexpectedly
2022-01-12T13:51:41.293212Z DEBUG accepted connection from 127.0.0.1:41520
2022-01-12T13:51:41.301188Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: start handshake with wal proposer 127.0.0.1:41520 sysid 7052316959039522829 timeline 0
2022-01-12T13:51:41.301478Z  INFO callmemaybe. subscription already exists SubscriptionState { tenantid: ZTenantId(ZId([70, 225, 47, 142, 65, 124, 75, 208, 162, 113, 124, 197, 158, 16, 188, 193])), timelineid: ZTimelineId(ZId([91, 251, 189, 228, 76, 149, 31, 15, 247, 220, 151, 60, 116, 18, 6, 10])), pageserver_connstr: "postgresql://no_user:@localhost:15000", handle: None, last_call_time: Instant { tv_sec: 2238628, tv_nsec: 548734828 }, paused: false }
2022-01-12T13:51:41.301566Z  INFO new call spawned. time Instant { tv_sec: 2238628, tv_nsec: 791091978 }
            tenantid: 46e12f8e417c4bd0a2717cc59e10bcc1, timelineid: 5bfbbde44c951f0ff7dc973c7412060a
2022-01-12T13:51:41.301606Z  INFO callmemaybe. thread_main. subscribe callback request for timelineid=5bfbbde44c951f0ff7dc973c7412060a tenantid=46e12f8e417c4bd0a2717cc59e10bcc1
2022-01-12T13:51:41.301673Z  WARN callback task for timelineid=5bfbbde44c951f0ff7dc973c7412060a tenantid=46e12f8e417c4bd0a2717cc59e10bcc1 was cancelled before spawning a new one
2022-01-12T13:51:41.307722Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed greeting from proposer [101, 34, 23, 147, 216, 132, 9, 16, 172, 151, 240, 222, 84, 181, 71, 240], sending term 1
2022-01-12T13:51:41.311883Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed VoteRequest for term 2: VoteResponse { term: 2, vote_given: 1, flush_lsn: 0/0, truncate_lsn: 0/0, term_history: [] }
2022-01-12T13:51:41.312207Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: received ProposerElected ProposerElected { term: 2, start_streaming_at: 0/169ABB0, term_history: [(2, 0/169ABB0)] }
2022-01-12T13:51:41.315806Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: start receiving WAL since 0/169ABB0
2022-01-12T13:51:41.348603Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: restart decoder from 0/0 to 0/169ABB0
2022-01-12T13:51:41.353025Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 56, end_lsn=0/169ABE8, commit_lsn=0/0, truncate_lsn=0/169ABB0, resp AppendResponse { term: 2, flush_lsn: 0/169ABE8, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:41.353347Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 0, end_lsn=0/169ABE8, commit_lsn=0/169ABE8, truncate_lsn=0/169ABE8, resp AppendResponse { term: 2, flush_lsn: 0/169ABE8, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:41.452887Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 127432, end_lsn=0/16B9DB0, commit_lsn=0/169ABE8, truncate_lsn=0/169ABE8, resp AppendResponse { term: 2, flush_lsn: 0/16B9DB0, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:41.453157Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 0, end_lsn=0/16B9DB0, commit_lsn=0/16B9DB0, truncate_lsn=0/16B9DB0, resp AppendResponse { term: 2, flush_lsn: 0/16B9DB0, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:41.990752Z  INFO new call spawned. time Instant { tv_sec: 2238629, tv_nsec: 480257930 }
            tenantid: 46e12f8e417c4bd0a2717cc59e10bcc1, timelineid: 5bfbbde44c951f0ff7dc973c7412060a
2022-01-12T13:51:41.990911Z  INFO callmemaybe request_callback Connecting to pageserver postgresql://no_user:@localhost:15000
2022-01-12T13:51:41.992370Z DEBUG executing simple query: callmemaybe 46e12f8e417c4bd0a2717cc59e10bcc1 5bfbbde44c951f0ff7dc973c7412060a host=localhost port=15002 options='-c ztimelineid=5bfbbde44c951f0ff7dc973c7412060a ztenantid=46e12f8e417c4bd0a2717cc59e10bcc1'    
2022-01-12T13:51:41.995292Z DEBUG accepted connection from 127.0.0.1:41538
2022-01-12T13:51:42.016818Z  INFO {tid=8}:WAL sender{timeline=5bfbbde44c951f0ff7dc973c7412060a}: Start replication from 0/169ABB0 till None
2022-01-12T13:51:42.017028Z  INFO callmemaybe. thread_main. pause callback request for timelineid=5bfbbde44c951f0ff7dc973c7412060a tenantid=46e12f8e417c4bd0a2717cc59e10bcc1
2022-01-12T13:51:42.017438Z  INFO {tid=8}:WAL sender{timeline=5bfbbde44c951f0ff7dc973c7412060a}: sent WAL up to 0/16B9DB0
2022-01-12T13:51:42.030299Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 47256, end_lsn=0/16C5648, commit_lsn=0/16B9DB0, truncate_lsn=0/16B9DB0, resp AppendResponse { term: 2, flush_lsn: 0/16C5648, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.030501Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 0, end_lsn=0/16C5648, commit_lsn=0/16C5648, truncate_lsn=0/16C5648, resp AppendResponse { term: 2, flush_lsn: 0/16C5648, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.030658Z  INFO {tid=8}:WAL sender{timeline=5bfbbde44c951f0ff7dc973c7412060a}: sent WAL up to 0/16C5648
2022-01-12T13:51:42.038169Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 8272, end_lsn=0/16C7698, commit_lsn=0/16C5648, truncate_lsn=0/16C5648, resp AppendResponse { term: 2, flush_lsn: 0/16C7698, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.038360Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 0, end_lsn=0/16C7698, commit_lsn=0/16C7698, truncate_lsn=0/16C7698, resp AppendResponse { term: 2, flush_lsn: 0/16C7698, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.038475Z  INFO {tid=8}:WAL sender{timeline=5bfbbde44c951f0ff7dc973c7412060a}: sent WAL up to 0/16C7698
2022-01-12T13:51:42.039317Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 8272, end_lsn=0/16C96E8, commit_lsn=0/16C7698, truncate_lsn=0/16C7698, resp AppendResponse { term: 2, flush_lsn: 0/16C96E8, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.039474Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 0, end_lsn=0/16C96E8, commit_lsn=0/16C96E8, truncate_lsn=0/16C96E8, resp AppendResponse { term: 2, flush_lsn: 0/16C96E8, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.039573Z  INFO {tid=8}:WAL sender{timeline=5bfbbde44c951f0ff7dc973c7412060a}: sent WAL up to 0/16C96E8
2022-01-12T13:51:42.041861Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 9432, end_lsn=0/16CBBC0, commit_lsn=0/16C96E8, truncate_lsn=0/16C96E8, resp AppendResponse { term: 2, flush_lsn: 0/16CBBC0, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.042014Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 0, end_lsn=0/16CBBC0, commit_lsn=0/16CBBC0, truncate_lsn=0/16CBBC0, resp AppendResponse { term: 2, flush_lsn: 0/16CBBC0, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.042111Z  INFO {tid=8}:WAL sender{timeline=5bfbbde44c951f0ff7dc973c7412060a}: sent WAL up to 0/16CBBC0
2022-01-12T13:51:42.046195Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 26016, end_lsn=0/16D2160, commit_lsn=0/16CBBC0, truncate_lsn=0/16CBBC0, resp AppendResponse { term: 2, flush_lsn: 0/16D2160, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.046364Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 0, end_lsn=0/16D2160, commit_lsn=0/16D2160, truncate_lsn=0/16D2160, resp AppendResponse { term: 2, flush_lsn: 0/16D2160, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.046458Z  INFO {tid=8}:WAL sender{timeline=5bfbbde44c951f0ff7dc973c7412060a}: sent WAL up to 0/16D2160
2022-01-12T13:51:42.049955Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 1584, end_lsn=0/16D2790, commit_lsn=0/16D2160, truncate_lsn=0/16D2160, resp AppendResponse { term: 2, flush_lsn: 0/16D2790, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.050143Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 0, end_lsn=0/16D2790, commit_lsn=0/16D2790, truncate_lsn=0/16D2790, resp AppendResponse { term: 2, flush_lsn: 0/16D2790, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.050283Z  INFO {tid=8}:WAL sender{timeline=5bfbbde44c951f0ff7dc973c7412060a}: sent WAL up to 0/16D2790
2022-01-12T13:51:42.291754Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 0, end_lsn=0/16D2790, commit_lsn=0/16D2790, truncate_lsn=0/16D2790, resp AppendResponse { term: 2, flush_lsn: 0/16D2790, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:42.990452Z DEBUG ignore call request for paused subscription
                tenantid: 46e12f8e417c4bd0a2717cc59e10bcc1, timelineid: 5bfbbde44c951f0ff7dc973c7412060a
2022-01-12T13:51:43.292217Z  INFO {tid=6}:WAL acceptor{timeline=5bfbbde44c951f0ff7dc973c7412060a}: processed AppendRequest of len 0, end_lsn=0/16D2790, commit_lsn=0/16D2790, truncate_lsn=0/16D2790, resp AppendResponse { term: 2, flush_lsn: 0/16D2790, commit_lsn: 0/0, disk_consistent_lsn: 0/0, hs_feedback: HotStandbyFeedback { ts: 0, xmin: 0, catalog_xmin: 0 } }
2022-01-12T13:51:43.990894Z DEBUG ignore call request for paused subscription
                tenantid: 46e12f8e417c4bd0a2717cc59e10bcc1, timelineid: 5bfbbde44c951f0ff7dc973c7412060a
2022-01-12T13:51:44.068266Z  WARN {tid=6}: query handler for START_WAL_PUSH postgresql://no_user:@localhost:15000 failed: failed to run ReceiveWalConn: connection closed unexpectedly
2022-01-12T13:51:44.990370Z DEBUG ignore call request for paused subscription
                tenantid: 46e12f8e417c4bd0a2717cc59e10bcc1, timelineid: 5bfbbde44c951f0ff7dc973c7412060a
thread 'WAL service thread' panicked at 'called `Option::unwrap()` on a `None` value', walkeeper/src/timeline.rs:247:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:735:21
   4: walkeeper::timeline::Timeline::check_stop_streaming
             at /home/arthur/zenith/walkeeper/src/timeline.rs:247:33
   5: walkeeper::send_wal::ReplicationConn::run
             at /home/arthur/zenith/walkeeper/src/send_wal.rs:292:24
   6: <walkeeper::handler::SafekeeperPostgresHandler as zenith_utils::postgres_backend::Handler>::process_query
             at /home/arthur/zenith/walkeeper/src/handler.rs:134:17
   7: zenith_utils::postgres_backend::PostgresBackend::process_message
             at /home/arthur/zenith/zenith_utils/src/postgres_backend.rs:434:33
   8: zenith_utils::postgres_backend::PostgresBackend::run_message_loop
             at /home/arthur/zenith/zenith_utils/src/postgres_backend.rs:283:31
   9: zenith_utils::postgres_backend::PostgresBackend::run
             at /home/arthur/zenith/zenith_utils/src/postgres_backend.rs:265:19
  10: walkeeper::wal_service::handle_socket
             at /home/arthur/zenith/walkeeper/src/wal_service.rs:66:5
  11: walkeeper::wal_service::thread_main::{{closure}}
             at /home/arthur/zenith/walkeeper/src/wal_service.rs:33:43
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-01-12T13:51:45.203104Z DEBUG {tid=8}:WAL sender{timeline=5bfbbde44c951f0ff7dc973c7412060a}: Connection to pageserver is gone. Resume callmemeybe subsciption if necessary. tenantid 46e12f8e417c4bd0a2717cc59e10bcc1 timelineid 5bfbbde44c951f0ff7dc973c7412060a
2022-01-12T13:51:45.203419Z  INFO callmemaybe. thread_main. resume callback request for timelineid=5bfbbde44c951f0ff7dc973c7412060a tenantid=46e12f8e417c4bd0a2717cc59e10bcc1
2022-01-12T13:51:45.990632Z  INFO new call spawned. time Instant { tv_sec: 2238633, tv_nsec: 480137839 }
            tenantid: 46e12f8e417c4bd0a2717cc59e10bcc1, timelineid: 5bfbbde44c951f0ff7dc973c7412060a
2022-01-12T13:51:45.990755Z  INFO callmemaybe request_callback Connecting to pageserver postgresql://no_user:@localhost:15000
2022-01-12T13:51:45.993332Z DEBUG executing simple query: callmemaybe 46e12f8e417c4bd0a2717cc59e10bcc1 5bfbbde44c951f0ff7dc973c7412060a host=localhost port=15002 options='-c ztimelineid=5bfbbde44c951f0ff7dc973c7412060a ztenantid=46e12f8e417c4bd0a2717cc59e10bcc1'    
2022-01-12T13:51:45.995263Z ERROR callback task for timelineid=5bfbbde44c951f0ff7dc973c7412060a tenantid=46e12f8e417c4bd0a2717cc59e10bcc1 failed: db error: ERROR: Failed to fetch local timeline for callmemaybe requests
2022-01-12T13:51:46.990749Z  INFO new call spawned. time Instant { tv_sec: 2238634, tv_nsec: 480254464 }
            tenantid: 46e12f8e417c4bd0a2717cc59e10bcc1, timelineid: 5bfbbde44c951f0ff7dc973c7412060a
```
</details>

Maybe the bug is connected to the fact that we run "different" pageservers in this test.

**Comment by LizardWizzard** [comment]
Just catched it locally.
I have a test with multiple pageservers and this occurs when I restart compute node which leads to sync safekeepers hang forever. Reproduced on each run. I see  connection reset by peer error several messages earlier in the log so this is probably the cause why this option become none

```
2022-01-12T12:57:49.243823Z  INFO {tid=7}:WAL sender{timeline=205b4c15bc469d088855b29a932004b7 pageserver_connstr=postgresql://no_user:@localhost:15000}: sent WAL up to 0/3BADC90
2022-01-12T12:57:49.243824Z  INFO {tid=10}:WAL sender{timeline=205b4c15bc469d088855b29a932004b7 pageserver_connstr=postgresql://no_user:@localhost:15005}: sent WAL up to 0/3BADC90
2022-01-12T12:57:49.249381Z ERROR Replication background thread failed: Connection reset by peer (os error 104)
2022-01-12T12:57:49.255751Z  WARN {tid=9}: query handler for START_WAL_PUSH postgresql://no_user:@localhost:15000 failed: failed to run ReceiveWalConn: connection closed unexpectedly
2022-01-12T12:57:49.442833Z DEBUG ignore call request for paused subscription tenantid: 74ee8b079a0e437eb0afea7d26a07209, timelineid: 205b4c15bc469d088855b29a932004b7
2022-01-12T12:57:49.442895Z DEBUG ignore call request for paused subscription tenantid: 74ee8b079a0e437eb0afea7d26a07209, timelineid: 205b4c15bc469d088855b29a932004b7
thread 'WAL service thread' panicked at 'called `Option::unwrap()` on a `None` value', walkeeper/src/timeline.rs:246:67
stack backtrace:
2022-01-12T12:57:50.243999Z DEBUG {tid=7}:WAL sender{timeline=205b4c15bc469d088855b29a932004b7 pageserver_connstr=postgresql://no_user:@localhost:15000}: Connection to pageserver is gone. Resume callmemeybe subsciption if necessary. tenantid 74ee8b079a0e437eb0afea7d26a07209 timelineid 205b4c15bc469d088855b29a932004b7
2022-01-12T12:57:50.244117Z DEBUG callmemaybe: unsubscribe{timelineid=205b4c15bc469d088855b29a932004b7 tenantid=74ee8b079a0e437eb0afea7d26a07209 pageserver_connstr=postgresql://no_user:@localhost:15000}: unsubscribe
2022-01-12T12:57:50.244132Z  WARN {tid=7}: query handler for START_REPLICATION PHYSICAL 0/170DFF8 failed: failed to run ReplicationConn: end streaming to Some("pageserver")
2022-01-12T12:57:50.244211Z DEBUG callmemaybe. thread_main. resume callback request for timelineid=205b4c15bc469d088855b29a932004b7 tenantid=74ee8b079a0e437eb0afea7d26a07209 pageserver_connstr=postgresql://no_user:@localhost:15000
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:746:21
   4: walkeeper::timeline::Timeline::check_stop_streaming
             at /home/dmitry/wrk/zenith/walkeeper/src/timeline.rs:246:33
   5: walkeeper::send_wal::ReplicationConn::run
             at /home/dmitry/wrk/zenith/walkeeper/src/send_wal.rs:305:24
   6: <walkeeper::handler::SafekeeperPostgresHandler as zenith_utils::postgres_backend::Handler>::process_query
             at /home/dmitry/wrk/zenith/walkeeper/src/handler.rs:137:17
   7: zenith_utils::postgres_backend::PostgresBackend::process_message
             at /home/dmitry/wrk/zenith/zenith_utils/src/postgres_backend.rs:434:33
   8: zenith_utils::postgres_backend::PostgresBackend::run_message_loop
             at /home/dmitry/wrk/zenith/zenith_utils/src/postgres_backend.rs:283:31
   9: zenith_utils::postgres_backend::PostgresBackend::run
             at /home/dmitry/wrk/zenith/zenith_utils/src/postgres_backend.rs:265:19
  10: walkeeper::wal_service::handle_socket
             at /home/dmitry/wrk/zenith/walkeeper/src/wal_service.rs:66:5
  11: walkeeper::wal_service::thread_main::{{closure}}
             at /home/dmitry/wrk/zenith/walkeeper/src/wal_service.rs:33:43
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'HotStandbyFeedback thread' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', walkeeper/src/timeline.rs:300:50
```

**Comment by hlinnaka** [comment]
I just bumped into this on my laptop too. Looking at the code, I think there's a race condition between ReplicationConn::run() finishing, and background_thread() finishing. The drop of ReplicationConnGuard removes the entry from the 'replicas' array, and the ReplicationConnGuard is handled by the background thread. So if the background thread finishes first, the call to check_stop_streaming() in the main thread will panic.

That seems pretty straightforward to fix, so I'll take a stab at it.
