### ISSUE TITLE
Panic in cli start

### ISSUE THREAD

**Issue by dhammika** [zenithdb/zenith#1260]
Build:
```
./target/debug/zenith -V
Zenith CLI git:b51f23cdf060e14723a3847d6a3767370588ef3f-modified
```

```
./target/debug/zenith start
thread 'main' panicked at '`pageserver-config-override` is not a name of an argument or a group.
Make sure you're using the name of the argument itself and not the name of short or long flags.', /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.14/src/parse/matches/arg_matches.rs:283:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: clap::parse::matches::arg_matches::ArgMatches::get_arg
             at /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.14/src/parse/matches/arg_matches.rs:1080:17
   3: clap::parse::matches::arg_matches::ArgMatches::values_of
             at /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.14/src/parse/matches/arg_matches.rs:283:19
   4: zenith::pageserver_config_overrides
             at ./zenith/src/main.rs:428:5
   5: zenith::handle_start_all
             at ./zenith/src/main.rs:691:39
   6: zenith::main
             at ./zenith/src/main.rs:239:24
   7: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
```

**Comment by hlinnaka** [comment]
Looks like this was broken by commit 76b74349cbed8ef2f64c19f8b991526d69287a24. I'm a bit surprised it didn't cause any tests to fail, I guess that's because the python tests use "zenith pageserver/safekeeper/pg start" commands rather than just "zenith start".

**Comment by dhammika** [comment]
Verified in main, 

```
./target/debug/zenith -V
Zenith CLI git:d951dd8977a06f98de9640bcff7ff1977665bca1-modified

./target/debug/zenith start
Starting pageserver at '127.0.0.1:64000' in '.zenith'
Pageserver started
initializing for single for 7676
Starting safekeeper at '127.0.0.1:5454' in '.zenith/safekeepers/single'
Safekeeper started
```
