### ISSUE TITLE
Crash at "VACUUM FULL pg_class"

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#25]
```
psql (14devel)
Type "help" for help.

regression=# vacuum full pg_class;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: WARNING:  terminating connection because of crash of another server process
```
Backtrace:
```
Core was generated by `postgres: zenith postgres [local] VACUUM                '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055f6917bffd3 in RelationReloadNailed (relation=0x7fdacb6eaef0) at relcache.c:2338
2338				relp = (Form_pg_class) GETSTRUCT(pg_class_tuple);
(gdb) bt
#0  0x000055f6917bffd3 in RelationReloadNailed (relation=0x7fdacb6eaef0) at relcache.c:2338
zenithdb/postgres#1  0x000055f6917c0448 in RelationClearRelation (relation=0x7fdacb6eaef0, rebuild=true) at relcache.c:2476
zenithdb/postgres#2  0x000055f6917c0b07 in RelationFlushRelation (relation=0x7fdacb6eaef0) at relcache.c:2739
zenithdb/postgres#3  0x000055f6917c0caf in RelationCacheInvalidateEntry (relationId=1259) at relcache.c:2810
zenithdb/postgres#4  0x000055f6917b17cb in LocalExecuteInvalidationMessage (msg=0x55f692e58918) at inval.c:595
zenithdb/postgres#5  0x000055f6917b151f in ProcessInvalidationMessages (hdr=0x55f692de5b60, func=0x55f6917b16c4 <LocalExecuteInvalidationMessage>) at inval.c:466
zenithdb/postgres#6  0x000055f6917b20cc in CommandEndInvalidationMessages () at inval.c:1098
zenithdb/postgres#7  0x000055f69123e754 in AtCCI_LocalCache () at xact.c:1488
zenithdb/postgres#8  0x000055f69123e138 in CommandCounterIncrement () at xact.c:1058
zenithdb/postgres#9  0x000055f6912899b7 in reindex_relation (relid=1259, flags=18, params=0x7ffdbec14658) at index.c:3998
zenithdb/postgres#10 0x000055f691337d0b in finish_heap_swap (OIDOldHeap=1259, OIDNewHeap=16384, is_system_catalog=true, swap_toast_by_content=false, check_constraints=false, is_internal=true, 
    frozenXid=539, cutoffMulti=1, newrelpersistence=112 'p') at cluster.c:1418
zenithdb/postgres#11 0x000055f6913367ab in rebuild_relation (OldHeap=0x7fdacb6eaef0, indexOid=0, verbose=false) at cluster.c:611
zenithdb/postgres#12 0x000055f6913361e3 in cluster_rel (tableOid=1259, indexOid=0, params=0x7ffdbec14788) at cluster.c:427
zenithdb/postgres#13 0x000055f6913d9b94 in vacuum_rel (relid=1259, relation=0x55f692d63a60, params=0x7ffdbec14990) at vacuum.c:1940
zenithdb/postgres#14 0x000055f6913d7b98 in vacuum (relations=0x55f692e3d618, params=0x7ffdbec14990, bstrategy=0x55f692e3d4f0, isTopLevel=true) at vacuum.c:459
zenithdb/postgres#15 0x000055f6913d7636 in ExecVacuum (pstate=0x55f692d84a80, vacstmt=0x55f692d63b48, isTopLevel=true) at vacuum.c:252
zenithdb/postgres#16 0x000055f69163ec57 in standard_ProcessUtility (pstmt=0x55f692d63f48, queryString=0x55f692d63040 "vacuum full pg_class;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, 
    dest=0x55f692d64038, qc=0x7ffdbec14dd0) at utility.c:826
zenithdb/postgres#17 0x000055f69163e42f in ProcessUtility (pstmt=0x55f692d63f48, queryString=0x55f692d63040 "vacuum full pg_class;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, 
    dest=0x55f692d64038, qc=0x7ffdbec14dd0) at utility.c:525
zenithdb/postgres#18 0x000055f69163d1d9 in PortalRunUtility (portal=0x55f692dc8860, pstmt=0x55f692d63f48, isTopLevel=true, setHoldSnapshot=false, dest=0x55f692d64038, qc=0x7ffdbec14dd0) at pquery.c:1159
zenithdb/postgres#19 0x000055f69163d406 in PortalRunMulti (portal=0x55f692dc8860, isTopLevel=true, setHoldSnapshot=false, dest=0x55f692d64038, altdest=0x55f692d64038, qc=0x7ffdbec14dd0) at pquery.c:1305
zenithdb/postgres#20 0x000055f69163c8e1 in PortalRun (portal=0x55f692dc8860, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x55f692d64038, altdest=0x55f692d64038, qc=0x7ffdbec14dd0)
    at pquery.c:779
zenithdb/postgres#21 0x000055f691636409 in exec_simple_query (query_string=0x55f692d63040 "vacuum full pg_class;") at postgres.c:1240
zenithdb/postgres#22 0x000055f69163a958 in PostgresMain (argc=1, argv=0x7ffdbec15060, dbname=0x55f692d90748 "postgres", username=0x55f692d90728 "zenith") at postgres.c:4394
zenithdb/postgres#23 0x000055f691574241 in BackendRun (port=0x55f692d84320) at postmaster.c:4484
zenithdb/postgres#24 0x000055f691573b73 in BackendStartup (port=0x55f692d84320) at postmaster.c:4206
zenithdb/postgres#25 0x000055f69156ff0f in ServerLoop () at postmaster.c:1730
zenithdb/postgres#26 0x000055f69156f75c in PostmasterMain (argc=3, argv=0x55f692d5c9b0) at postmaster.c:1402
zenithdb/postgres#27 0x000055f69146e9fa in main (argc=3, argv=0x55f692d5c9b0) at main.c:213
```
This happens in the 'vacuum` regression test.

**Comment by kelvich** [comment]
related to #113

**Comment by hlinnaka** [comment]
Doesn't crash anymore
