### ISSUE TITLE
panic in layered_repo in test_race_conditions in CI

### ISSUE THREAD

**Issue by LizardWizzard** [zenithdb/zenith#513]
stacktrace
```
Sep 01 10:04:38.399 INFO WAL streaming connection failed (connection closed), retrying in 1 second, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:110
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', pageserver/src/layered_repository.rs:970:61
stack backtrace:
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', pageserver/src/layered_repository.rs:970:61
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:386:21
   4: pageserver::layered_repository::LayeredTimeline::get_layer_for_read
             at /home/circleci/project/pageserver/src/layered_repository.rs:970:25
   5: <pageserver::layered_repository::LayeredTimeline as pageserver::repository::Timeline>::get_relish_size
             at /home/circleci/project/pageserver/src/layered_repository.rs:563:41
   6: pageserver::page_service::PageServerHandler::handle_pagerequests::{{closure}}
             at /home/circleci/project/pageserver/src/page_service.rs:285:29
   7: prometheus::histogram::Histogram::observe_closure_duration
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.12.0/src/histogram.rs:715:19
   8: pageserver::page_service::PageServerHandler::handle_pagerequests
             at /home/circleci/project/pageserver/src/page_service.rs:280:36
   9: <pageserver::page_service::PageServerHandler as zenith_utils::postgres_backend::Handler>::process_query
             at /home/circleci/project/pageserver/src/page_service.rs:446:13
  10: zenith_utils::postgres_backend::PostgresBackend::process_message
             at /home/circleci/project/zenith_utils/src/postgres_backend.rs:304:33
  11: zenith_utils::postgres_backend::PostgresBackend::run_message_loop
             at /home/circleci/project/zenith_utils/src/postgres_backend.rs:194:19
  12: zenith_utils::postgres_backend::PostgresBackend::run
             at /home/circleci/project/zenith_utils/src/postgres_backend.rs:180:19
  13: pageserver::page_service::page_service_conn_main
             at /home/circleci/project/pageserver/src/page_service.rs:180:5
  14: pageserver::page_service::thread_main::{{closure}}
             at /home/circleci/project/pageserver/src/page_service.rs:156:31
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:386:21
   4: pageserver::layered_repository::LayeredTimeline::get_layer_for_read
             at /home/circleci/project/pageserver/src/layered_repository.rs:970:25
   5: <pageserver::layered_repository::LayeredTimeline as pageserver::repository::Timeline>::get_relish_size
             at /home/circleci/project/pageserver/src/layered_repository.rs:563:41
   6: pageserver::page_service::PageServerHandler::handle_pagerequests::{{closure}}
             at /home/circleci/project/pageserver/src/page_service.rs:285:29
   7: prometheus::histogram::Histogram::observe_closure_duration
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.12.0/src/histogram.rs:715:19
   8: pageserver::page_service::PageServerHandler::handle_pagerequests
             at /home/circleci/project/pageserver/src/page_service.rs:280:36
   9: <pageserver::page_service::PageServerHandler as zenith_utils::postgres_backend::Handler>::process_query
             at /home/circleci/project/pageserver/src/page_service.rs:446:13
  10: zenith_utils::postgres_backend::PostgresBackend::process_message
             at /home/circleci/project/zenith_utils/src/postgres_backend.rs:304:33
  11: zenith_utils::postgres_backend::PostgresBackend::run_message_loop
             at /home/circleci/project/zenith_utils/src/postgres_backend.rs:194:19
  12: zenith_utils::postgres_backend::PostgresBackend::run
             at /home/circleci/project/zenith_utils/src/postgres_backend.rs:180:19
  13: pageserver::page_service::page_service_conn_main
             at /home/circleci/project/pageserver/src/page_service.rs:180:5
  14: pageserver::page_service::thread_main::{{closure}}
             at /home/circleci/project/pageserver/src/page_service.rs:156:31
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
cc @hlinnaka 

CI run: https://app.circleci.com/pipelines/github/zenithdb/zenith/1514/workflows/a24521ff-df71-4102-a905-9e0274fed4a5/jobs/9130/artifacts

**Comment by LizardWizzard** [comment]
This is this line in `get_layer_for_write`: `timeline = timeline.ancestor_timeline.as_ref().unwrap();` 
The issue is that LSN passed to `get_layer_for_write` was smaller than timeline.ancestor_lsn but there was no ancestor timeline in there. 

Note that ancestor_lsn is not optional, so it is always set to timeline start_lsn. But I wonder if it is a root timeline it's start lsn should be around zero so retrieving that data doesn't make any sense. 

I'll try to reproduce this, maybe it is gone after fixes that just landed

**Comment by LizardWizzard** [comment]
I tried to reproduce this and after another update to new main branch error seems to be gone. Closing the issue, will reopen if error shows up again
